// server/models/Review.js

const mongoose = require('mongoose');

// Define a schema for the structured review report output from the AI.
// We will store the AI's response as a plain object/JSON string.
const reviewSchema = new mongoose.Schema({
  userId: {
    // Links this review directly to the User who submitted it
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'User', // References the 'User' model
  },
  code: {
    // The raw code submitted by the user
    type: String,
    required: true,
  },
  language: {
    // The language of the code (e.g., 'javascript', 'python')
    type: String,
    required: true,
  },
  reviewReport: {
    // The structured JSON report generated by the Gemini AI.
    // Stored as a generic object or a stringified JSON.
    // Using a flexible SchemaType here allows us to store the complex structured output.
    type: mongoose.Schema.Types.Mixed,
    required: true,
  },
}, {
  timestamps: { createdAt: 'submissionDate', updatedAt: false } // Only record submission date
});

const Review = mongoose.model('Review', reviewSchema);

module.exports = Review;